### ISSUE TITLE
Integrate a git hook for enforcing and validating conventional commit style

### ISSUE THREAD

**Issue by davidzlu** [cognovi-ai/the-cdj#197]
The project uses conventional commits, but style is currently enforced only through code reviews. Integrating more automation into this would standardize the commit message style, and allow contributors and reviewers to focus on code over process.

One library that could implement this is: https://github.com/qoomon/git-conventional-commits

**Comment by hiyaryan** [comment]
This is a great idea! Here's some additional resources I found that we can look into.

[Conventional Commit Standard](https://www.conventionalcommits.org/en/v1.0.0/)

1.	[Customizable Conventional Commits](https://github.com/marketplace/actions/customizable-conventional-commits?utm_source=chatgpt.com): This action ensures all commit messages follow the Conventional Commits spec. You can tweak the allowed commit types to fit a project’s needs. ￼


	2.	[Conventional Commits PR](https://github.com/marketplace/actions/conventional-commits-pr?utm_source=chatgpt.com): This action validates pull request titles against the Conventional Commits preset. This is useful for squash merges.

	3.	[Conventional PR Title](https://github.com/marketplace/actions/conventional-pr-title?utm_source=chatgpt.com): Checks that PR titles match the Conventional Commits spec. Helpful when using semantic-release with the Conventional Commits preset. ￼

	4.	[Conventional Commits GitHub Action](https://github.com/webiny/action-conventional-commits?utm_source=chatgpt.com): Verifies all commit messages adhere to the Conventional Commits specification.

To set up any of these actions, add a workflow file in .github/workflows directory. Example using the Customizable Conventional Commits action:

```
name: Conventional Commits
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gentleseal/action-conventional-commits@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

This setup will check that all commit messages in your pull requests follow the Conventional Commits standard. You can customize the valid-commit-types parameter to specify which commit types are allowed.

By integrating one of these actions into your workflow, you can keep your commit history clean and consistent, making collaboration smoother and your project’s history easier to navigate.
